### ISSUE TITLE
dynlib uses wrong .so file when linking

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-rocksdb#10]
On linux, the wrapper currently links to `librocksdb.so` which is loaded at runtime (due to how nim handles .so loading, via dlopen) - this is problematic because:

* `librocksdb.so` is only installed as part of `-devel` packages on distributions - it's only supposed to be used during development, together with the header files that come in the same package, not when running the application
* ABI versioning is broken - `.so` without version typically links to latest version - if this is not the same as was used while writing the wrapper, crashes and security issues may follow, now or in the future
* version incompatibility may for example happen when doing builds on a CI that runs a different linux version than what the binary is doing

on Fedora28, that ships with version `5.7.4`, the soname is `librocksdb.so.5.7` - this indicates that upstream developers keep ABI stable for patch versions only. On the other hand, specifying 5.7 is tricky from a maintenance perspective - this will require lots of testing with different versions to ensure that the wrapper is compatible with all of them. Ubuntu14.04 comes with rocksdb 4.x

The ABI/versioning problem is not linux-specific, but the way the .so-file is linked is.

**Comment by stefantalpalaru** [comment]
This is how Debian splits the shared libraries on installation:

https://sources.debian.org/src/rocksdb/5.17.2-3/debian/librocksdb5.17.install/

https://sources.debian.org/src/rocksdb/5.17.2-3/debian/librocksdb-dev.install/

**Comment by arnetheduck** [comment]
this is obsolete now that we build from source by default
