### ISSUE TITLE
`nimble test` and CI builds broken

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-rocksdb#11]
`nimble test`:
Doesn't run all tests - for whatever reason, there's a separate `test_c` command to run part of the test suite

Travis:
runs only c api tests, due to `nimble test_c` being separate from `nimble test`, and neither of them running all tests

AppVeyor:
See https://ci.appveyor.com/project/jarradh/nim-rocksdb/build/1.0.34:
```
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```

**Comment by cheatfate** [comment]
For some reason MacOS tests are also disabled.

**Comment by stefantalpalaru** [comment]
Fixed by https://github.com/status-im/nim-rocksdb/pull/17
