### ISSUE TITLE
Error: type mismatch: got <rocksdb_t, rocksdb_writeoptions_t, cstring, int, cstring, int, ptr cstring>

### ISSUE THREAD

**Issue by vulogov** [status-im/nim-rocksdb#23]
Got this during compilation of the sample program on OSX, nim 1.2.0, rocksdb-6.7.3.catalina.bottle.tar.gz

`r.nim(35, 14) Error: type mismatch: got <rocksdb_t, rocksdb_writeoptions_t, cstring, int, cstring, int, ptr cstring>
but expected one of:
proc rocksdb_put(db: rocksdb_t; options: rocksdb_writeoptions_t; key: cstring;
                keylen: csize_t; val: cstring; vallen: csize_t; errptr: ptr cstring)
  first type mismatch at position: 4
  required type for keylen: csize_t
  but expression 'len(key)' is of type: int

expression: rocksdb_put(db, writeOptions, cstring(key), len(key), cstring(put_value),
            len(put_value), addr(err))`

**Comment by xyb** [comment]
@vulogov I think #24 has solved this problem.

**Comment by mratsim** [comment]
you need to convert your input with `csize_t(x)`. csize_t is an unsigned int.
